import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "./globals.css";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "1. FCN Fußballschule",
  description: "Generated by create next app",
};

const theme = createTheme({
  primaryColor: "red",
  colors: {
    red: [
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
      "#AA1124",
    ],
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
